### ISSUE TITLE
ERROR: invalid tag

### ISSUE THREAD

**Issue by agent-squirrel** [VaultVulp/gp-docker-action#23]
I know this quite possibly something I have misconfigured but I'm pulling my hair out trying to find it. 

This is the content of my workflow file:

```
name: Docker CI/CD - Unstable
on:
  push:
    branches: [ unstable ]
  pull_request:
    branches: [ unstable ]

jobs:
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/unstable'
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          image: npp-orchestrator-unstable
          github-token: ${{ secrets.GH_TOKEN }}
          extract-git-tag: true
          additional-image-tags: unstable
          custom-args: --platform=linux/arm64,linux/amd64

  deploy:
    name: Call web hook to deploy container
    runs-on: ubuntu-latest
    needs: [build-docker]
    steps:
      - name: Deploy container
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DEPLOY_WEBHOOK_SIGNATURE }}
```
          
When running the workflow I get the following error:

`ERROR: invalid tag "ghcr.io/agent-squirrel/npp-app-test/:unstable": invalid reference format`

Is there something I'm missing or is this a bug perhaps?

Thanks

**Comment by VaultVulp** [comment]
Hi, @agent-squirrel !

I suggest to replace:
```yaml
          image: npp-orchestrator-unstable
```
with
```yaml
          image-name: npp-orchestrator-unstable
```

This should fix the issue.

**Comment by agent-squirrel** [comment]
Thanks for your help. It still seems to produce the same error however. 

If I remove the extract-git-tag key the build succeeds but it of course sets the tag to latest which is less than ideal.

**Comment by VaultVulp** [comment]
I see, it might be an issue with the way I hanlde  `extract-git-tag` and `additional-image-tags` arguments

--------

I provided the `extract-git-tag` argument to extract git tags from the current ref, like in this [example](https://github.com/VaultVulp/test-gp-docker-action/blob/master/.github/workflows/workflow.tag.yml)
Note:
```yaml
on: 
  push:
    tags:
    - "*"
 ```
and
```yaml
    if: startsWith(github.ref, 'refs/tags/') # Running this job only for tags
```

In your case, I suggest to separate one job into multiple workflows.
One for unstable branch with (with the current `on.push` and `on. pull_request` configuration):
```yaml
          image: npp-orchestrator-unstable
          github-token: ${{ secrets.GH_TOKEN }}
          additional-image-tags: unstable
          custom-args: --platform=linux/arm64,linux/amd64
```
and another one for tags (with the `on.push` and `on. pull_request` from the [example](https://github.com/VaultVulp/test-gp-docker-action/blob/master/.github/workflows/workflow.tag.yml)):
```yaml
          image: npp-orchestrator-unstable
          github-token: ${{ secrets.GH_TOKEN }}
          extract-git-tag: true
          custom-args: --platform=linux/arm64,linux/amd64
```
