### ISSUE TITLE
Support for Docker build-args 

### ISSUE THREAD

**Issue by jjoyce0510** [VaultVulp/gp-docker-action#4]
It does not appear as though support for providing [build-time arguments](https://vsupalov.com/docker-env-vars/) before publishing the image exists. Is there a plan to introduce it?

**Comment by VaultVulp** [comment]
Hello, @jjoyce0510 !

It seems like I was able to solve this issue with the latest release.

You can try to use custom args in a fashion similar to:

```YAML
  build-with-custom-args:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' # Running this job only for develop branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build with --build-arg(s)
      uses: VaultVulp/gp-docker-action@1.1.8
      with:
        custom-args: --build-arg some=value --build-arg some_other=value
```
