### ISSUE TITLE
(Question) Possibility or using mutliple tags for a single build

### ISSUE THREAD

**Issue by V-ed** [VaultVulp/gp-docker-action#7]
Is it possible to run a build and tag it with multiple tags?

The use case would be to use `extract-git-tag: true` while also updating a `latest` tag up to date.

Thanks in advance!

**Comment by VaultVulp** [comment]
Hi, V-ed, and thanks for your contribution! 

As far as I know - it's possible to do so. I'll add this feature in the near future.

I'm sure you already know this, but until this option is available, you can run this action multiple times in the same pipeline pushing two images subsequently.

**Comment by V-ed** [comment]
Interesting! Thanks for the heads up :)

And while I thought about running it twice indeed, I was thinking about the fact that it would essentially build twice for no reason, as it is the same image - I was already trying to optimize my pipelines haha

I also though about potentially using the `custom-args` option, but didn't try yet, with a (small) fear that it it would break the `extract-git-tag` option (by overriding the option of the docker command). If I ever get around to trying to use `custom-args` to add another image tag, I'll update the issue here.

**Comment by justinmchase** [comment]
This was the first thing I looked for, I generally want to generate 3 tags based on the version. I'd like to have this:

```yaml
    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: my-cool-service
        image-tags:
          - latest
          - "${{ steps.increment.outputs.version }}"
          - "${{ steps.increment.outputs.major }}.${{ steps.increment.outputs.minor }}"
```

**Comment by manang** [comment]
question: did you push this modification?
Thanks

**Comment by VaultVulp** [comment]
@manang Not yet, sadly.

**Comment by VaultVulp** [comment]
As far as I know, it's impossible to pass list values to the github actions.
So, the following syntax is invalid:
```yaml
      image-tags:
          - latest
          - "${{ steps.increment.outputs.version }}"
          - "${{ steps.increment.outputs.major }}.${{ steps.increment.outputs.minor }}"
```
but, I guess I could try to implement something similar to:
```yaml
    additional-image-tags: "foo bar buz" 
```

**Comment by VaultVulp** [comment]
Done!

Example workflow:
```yaml
name: Build and publish 

on: push

jobs:
  build-with-multiple-tags:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0 # Checking out the repo
 
    - name: Build with multiple tags
      uses: VaultVulp/gp-docker-action@1.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: my-cool-service # Provide Docker image name
        image-tags: first # if ommitted will be replaced with "latest"
        additional-image-tags: second third # two additional tags for an image
```
